config/routes.rb
Rails.application.routes.draw do
  resources :pedidos
  resources :tags
  resources :articulos
  devise_for :users
  resources :marcas
  # get "/details/new/articulo/:id", to: "details#new", as: "new_detail"
  root "articulos#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/pedido.rb
class Pedido < ApplicationRecord
  belongs_to :user
  has_many :details
  has_many :articulos, through: :details
end

app/controllers/pedidos_controller.rb
class PedidosController < ApplicationController
  before_action :authenticate_user!, except: :index
  before_action :permitted?, except: [:index, :show]
  before_action :set_pedido, only: %i[ show edit update destroy ]

  # GET /pedidos or /pedidos.json
  def index
    @pedidos = Pedido.all
  end

  # GET /pedidos/1 or /pedidos/1.json
  def show
    if @pedido.user_id != current_user.id
      redirect_to pedidos_url, alert: "Usted no puede consultar un  pedido ajeno"
    end
  end

  # GET /pedidos/new
  def new
    @pedido = Pedido.new
  end

  # GET /pedidos/1/edit
  def edit
    if @pedido.user_id != current_user.id
      redirect_to pedidos_url, alert: "Usted no es el propietario del pedido"
    end
  end

  # POST /pedidos or /pedidos.json
  def create
    @pedido = Pedido.new(pedido_params)

    respond_to do |format|
      if @pedido.save
        format.html { redirect_to pedido_url(@pedido), notice: "Pedido was successfully created." }
        format.json { render :show, status: :created, location: @pedido }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pedido.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pedidos/1 or /pedidos/1.json
  def update
    respond_to do |format|
      if @pedido.update(pedido_params)
        format.html { redirect_to pedido_url(@pedido), notice: "Pedido was successfully updated." }
        format.json { render :show, status: :ok, location: @pedido }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pedido.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pedidos/1 or /pedidos/1.json
  def destroy
    
    respond_to do |format|
      if @pedido.user_id != current_user.id
        format.html { redirect_to pedidos_url, notice: "No puede eliminar un pedido que no es suyo" }
      else
        @pedido.destroy
        format.html { redirect_to pedidos_url, notice: "Pedido was successfully destroyed." }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pedido
      @pedido = Pedido.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pedido_params
      params.require(:pedido).permit(:fechaEntrega, :user_id)
    end
end

app/helpers/pedidos_helper.rb
module PedidosHelper
end

app/views/pedidos/_form.html.erb
<%= form_with(model: pedido) do |form| %>
  <% if pedido.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(pedido.errors.count, "error") %> prohibited this pedido from being saved:</h2>

      <ul>
        <% pedido.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :fechaEntrega, style: "display: block" %>
    <%= form.date_field :fechaEntrega %>
  </div>

  <div>
    <%= form.hidden_field :user_id, value:current_user.id.to_i %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/pedidos/_pedido.html.erb
<div id="<%= dom_id pedido %>">
  <p>
    <strong>ID pedido:</strong>
    <%= pedido.id %>
  </p>
  <p>
    <strong>Fecha entrega:</strong>
    <%= pedido.fechaEntrega %>
  </p>

  <p>
    <strong>User:</strong>
    <%= pedido.user.email %>
  </p>

</div>

app/views/pedidos/edit.html.erb
<h1>Editing pedido</h1>

<%= render "form", pedido: @pedido %>

<br>

<div>
  <%= link_to "Show this pedido", @pedido %> |
  <%= link_to "Back to pedidos", pedidos_path %>
</div>

app/views/pedidos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Pedidos</h1>

<div id="pedidos">
  <% @pedidos.each do |pedido| %>
    <%= render pedido %>
    <p>
      <%= link_to "Show this pedido", pedido %>
    </p>
  <% end %>
</div>

<%= link_to "New pedido", new_pedido_path %>

app/views/pedidos/new.html.erb
<h1>New pedido</h1>

<%= render "form", pedido: @pedido %>

<br>

<div>
  <%= link_to "Back to pedidos", pedidos_path %>
</div>

app/views/pedidos/show.html.erb
<p style="color: green"><%= notice %></p>
<%= pp Detail.inspect %>
<%= render @pedido %>

<div>
  <%= link_to "Edit this pedido", edit_pedido_path(@pedido) %> |
  <%= link_to "Back to pedidos", pedidos_path %>

  <%= button_to "Destroy this pedido", @pedido, method: :delete %>
</div>