config/routes.rb
Rails.application.routes.draw do
  resources :pedidos
  resources :tags
  resources :articulos
  devise_for :users
  resources :marcas
  # get "/details/new/articulo/:id", to: "details#new", as: "new_detail"
  root "articulos#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/articulo.rb
class Articulo < ApplicationRecord
  belongs_to :marca
  belongs_to :user
  has_and_belongs_to_many :tags
  has_many :details
  has_many :pedidos, through: :details
  has_one_attached :fotos
end

app/controllers/articulos_controller.rb
class ArticulosController < ApplicationController
  before_action :authenticate_user!, except: :index
  before_action :permitted?, except: [:index, :show]
  before_action :set_articulo, only: %i[ show edit update destroy ]

  # GET /articulos or /articulos.json
  def index
    @articulos = Articulo.all
  end

  # GET /articulos/1 or /articulos/1.json
  def show
  end

  # GET /articulos/new
  def new
    @articulo = Articulo.new
    @marcas = Marca.all
    @tags = Tag.all
  end

  # GET /articulos/1/edit
  def edit
  end

  # POST /articulos or /articulos.json
  def create
    @articulo = Articulo.new(articulo_params)

    respond_to do |format|
      if @articulo.save
        format.html { redirect_to articulo_url(@articulo), notice: "Articulo was successfully created." }
        format.json { render :show, status: :created, location: @articulo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @articulo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articulos/1 or /articulos/1.json
  def update
    respond_to do |format|
      if @articulo.update(articulo_params)
        format.html { redirect_to articulo_url(@articulo), notice: "Articulo was successfully updated." }
        format.json { render :show, status: :ok, location: @articulo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @articulo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articulos/1 or /articulos/1.json
  def destroy
    @articulo.destroy

    respond_to do |format|
      format.html { redirect_to articulos_url, notice: "Articulo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_articulo
      @articulo = Articulo.find(params[:id])
      @marcas = Marca.all
      @tags = Tag.all
    end

    # Only allow a list of trusted parameters through.
    def articulo_params
      params.require(:articulo).permit(:nombre, :descripcion, :condicion, :precio, :marca_id, :user_id, :fotos,  tag_ids: []) 
    end

end

app/helpers/articulos_helper.rb
module ArticulosHelper
end

app/views/articulos/_articulo.html.erb
<div id="<%= dom_id articulo %>">
  <p>
    <strong>Nombre:</strong>
    <%= articulo.nombre %>
  </p>

  <p>
    <strong>Descripcion:</strong>
    <%= articulo.descripcion %>
  </p>

  <p>
    <strong>Condicion:</strong>
    <%= articulo.condicion %>
  </p>

  <p>
    <strong>Precio:</strong>
    <%= articulo.precio %>
  </p>

  <p>
    <strong>Marca:</strong>
    <%= articulo.marca.nombre %>
  </p>

  <p>
    <strong>Tags:</strong>
    <% articulo.tags.each do |t| %>
      <span>
        <%= t.name %>
      </span>
    <% end %>
  </p>

  <p>
    <% if articulo.fotos.attached? %>
        <%= image_tag articulo.fotos.variant(resize_to_limit: [150, 150]) %>
    <% end %>
  </p>
</div>

app/views/articulos/_form.html.erb
<%= form_with(model: articulo) do |form| %>
  <% if articulo.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(articulo.errors.count, "error") %> prohibited this articulo from being saved:</h2>

      <ul>
        <% articulo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nombre, style: "display: block" %>
    <%= form.text_field :nombre %>
  </div>

  <div>
    <%= form.label :descripcion, style: "display: block" %>
    <%= form.text_field :descripcion %>
  </div>

  <div>
    <%= form.label :condicion, style: "display: block" %>
    <%= form.text_field :condicion %>
  </div>

  <div>
    <%= form.label :precio, style: "display: block" %>
    <%= form.number_field :precio %>
  </div>

  <div>
    <%= form.label :marca_id, style: "display: block" %>
    <%= form.collection_select :marca_id, @marcas, :id, :nombre  %>
  </div>

  <div>
    <%= form.label :tags %>
    <%= form.collection_check_boxes :tag_ids, @tags, :id, :name %>
  </div>

  <div>
    <%= form.label :fotos %>
    <%= form.file_field :fotos %>
  </div>

  <div>
    <%#= form.label :user_id, style: "display: block" %>
    <%= form.hidden_field :user_id, value:current_user.id.to_i %>
  </div> 

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articulos/edit.html.erb
<h1>Editing articulo</h1>

<%= render "form", articulo: @articulo, tags: @tags %>

<br>

<div>
  <%= link_to "Show this articulo", @articulo %> |
  <%= link_to "Back to articulos", articulos_path %>
</div>

app/views/articulos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Articulos pa' la guagua</h1>

<div id="articulos">
  <% @articulos.each do |articulo| %>
    <%= render articulo %>
    <p>
      <%= link_to "Show this articulo", articulo %>
    </p>
  <% end %>
</div>

<%= link_to "New articulo", new_articulo_path %>

app/views/articulos/new.html.erb
<h1>New articulo</h1>

<%= render "form", articulo: @articulo, tags: @tags %>

<br>

<div>
  <%= link_to "Back to articulos", articulos_path %>
</div>

app/views/articulos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @articulo %>

<div>
  <%= link_to "Edit this articulo", edit_articulo_path(@articulo) %> |
  <%= link_to "Back to articulos", articulos_path %>

  <%= button_to "Destroy this articulo", @articulo, method: :delete %>
  <%# link_to "Agregar a un pedido", new_detail_path(@articulo) %>
</div>